"""tables created

Revision ID: 20c110e7dc9e
Revises: 
Create Date: 2023-04-25 15:54:25.288320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20c110e7dc9e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dustheads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('first_name', sa.String(length=32), nullable=False),
    sa.Column('last_name', sa.String(length=32), nullable=True),
    sa.Column('bio', sa.String(length=280), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dustheads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dustheads_username'), ['username'], unique=True)

    op.create_table('records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('genre', sa.String(length=64), nullable=False),
    sa.Column('artist', sa.String(length=255), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('copies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('dusthead_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dusthead_id'], ['dustheads.id'], name=op.f('fk_copies_dusthead_id_dustheads')),
    sa.ForeignKeyConstraint(['record_id'], ['records.id'], name=op.f('fk_copies_record_id_records')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=280), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('dusthead_id', sa.Integer(), nullable=False),
    sa.Column('copy_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['copy_id'], ['copies.id'], name=op.f('fk_comments_copy_id_copies')),
    sa.ForeignKeyConstraint(['dusthead_id'], ['dustheads.id'], name=op.f('fk_comments_dusthead_id_dustheads')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comments_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_timestamp'))

    op.drop_table('comments')
    op.drop_table('copies')
    op.drop_table('records')
    with op.batch_alter_table('dustheads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dustheads_username'))

    op.drop_table('dustheads')
    # ### end Alembic commands ###
