"""adding timestamps

Revision ID: 8d5009992092
Revises: b2b1e8daefec
Create Date: 2023-05-03 16:03:33.705777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d5009992092'
down_revision = 'b2b1e8daefec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_index('ix_comments_timestamp')
        batch_op.create_index(batch_op.f('ix_comments_created_at'), ['created_at'], unique=False)
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('copies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_copies_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('dustheads', schema=None) as batch_op:
        batch_op.drop_index('ix_dustheads_username')
        batch_op.create_index(batch_op.f('ix_dustheads_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dustheads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dustheads_username'))
        batch_op.create_index('ix_dustheads_username', ['username'], unique=False)

    with op.batch_alter_table('copies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_copies_created_at'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_comments_created_at'))
        batch_op.create_index('ix_comments_timestamp', ['timestamp'], unique=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
