"""unnullabled the password hash

Revision ID: b2b1e8daefec
Revises: 242818309d3e
Create Date: 2023-04-27 20:01:51.245425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2b1e8daefec'
down_revision = '242818309d3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index('ix_comments_timestamp')
        batch_op.create_index(batch_op.f('ix_comments_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('dustheads', schema=None) as batch_op:
        batch_op.alter_column('_password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_index('ix_dustheads_username')
        batch_op.create_index(batch_op.f('ix_dustheads_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dustheads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dustheads_username'))
        batch_op.create_index('ix_dustheads_username', ['username'], unique=False)
        batch_op.alter_column('_password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_timestamp'))
        batch_op.create_index('ix_comments_timestamp', ['timestamp'], unique=False)

    # ### end Alembic commands ###
