"""auth added

Revision ID: c520f757743f
Revises: 1cf3796f368c
Create Date: 2023-04-27 11:00:35.631475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c520f757743f'
down_revision = '1cf3796f368c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index('ix_comments_timestamp')
        batch_op.create_index(batch_op.f('ix_comments_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('dustheads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('_password_hash', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('password_confirmation', sa.String(), nullable=False))
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
        batch_op.drop_index('ix_dustheads_username')
        batch_op.create_index(batch_op.f('ix_dustheads_username'), ['username'], unique=True)
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dustheads', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_dustheads_username'))
        batch_op.create_index('ix_dustheads_username', ['username'], unique=False)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
        batch_op.drop_column('password_confirmation')
        batch_op.drop_column('_password_hash')
        batch_op.drop_column('email')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_timestamp'))
        batch_op.create_index('ix_comments_timestamp', ['timestamp'], unique=False)

    # ### end Alembic commands ###
